### ISSUE TITLE
getting unixPoster to work with Diagrams 1.3

### ISSUE THREAD

**Issue by NickAger** [tkvogt/unixPoster#2]
I'm relatively new to Haskell and am struggling to get unixPoster to compile with the latest code from Hackage. 
I see there is a migration guide here: https://wiki.haskell.org/Diagrams/Dev/Migrate1.3
but am defeated by errors such as:
```
poster.hs:40:23:
    Couldn't match type ‘String -> QDiagram b43 V2 n10 Any’
                   with ‘QDiagram b V2 n m’
    Expected type: (String -> QDiagram b43 V2 n10 Any)
                   -> QDiagram b V2 n m
      Actual type: QDiagram b V2 n m -> QDiagram b V2 n m
    Relevant bindings include
      unixPoster :: QDiagram b V2 n m (bound at poster.hs:38:1)
    In the second argument of ‘(#)’, namely ‘centerXY’
    In the second argument of ‘(===)’, namely ‘header # centerXY’
```

I've fixed some issues see https://github.com/NickAger/unixPoster/commit/ebeb9415cc4d9544e64f86c348b11810684678e5

but am now stuck. All idea gratefully received.

**Comment by tkvogt** [comment]
Fixed. The poster looks now a little bit different because of the new lineWidth functions.
